### ISSUE TITLE
大量のデータを同時の保存しようとすると強制終了発生

### ISSUE THREAD

**Issue by diffserve** [diffserve/voice_recorder_ymse3p#50]
2021-03-30 11:45:49.116 9707-9781/ymse3p.app.audiorecorder E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: ymse3p.app.audiorecorder, PID: 9707
    java.lang.ArrayIndexOutOfBoundsException: length=13; index=-606
        at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453)
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2411)
        at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2813)
        at java.util.Calendar.updateTime(Calendar.java:3403)
        at java.util.Calendar.getTimeInMillis(Calendar.java:1761)
        at java.util.Calendar.getTime(Calendar.java:1734)
        at java.text.SimpleDateFormat.parseInternal(SimpleDateFormat.java:1834)
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1728)
        at java.text.DateFormat.parse(DateFormat.java:360)
        at ymse3p.app.audiorecorder.data.database.AudioTypeConverter.stringToCalendar(AudioTypeConverter.kt:24)
        at ymse3p.app.audiorecorder.data.database.AudioDao_Impl$10.call(AudioDao_Impl.java:218)
        at ymse3p.app.audiorecorder.data.database.AudioDao_Impl$10.call(AudioDao_Impl.java:196)
        at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:81)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by diffserve** [comment]
SimpleDataFormatクラスがスレッドセーフではなかったことが原因。
このインスタンスをインスタンス変数からローカル変数に移したことで解決！
